#!/bin/bash
#run this in vim/ directory.

# A.  Create a Vim "runtime" subdirectory named "vim82"
VER=vim82
mkdir ${VER}
cp -r runtime/* ${VER}

# B.  Copy the new binaries into the "vim82" directory
find ./src -name *.exe -exec cp {} ${VER}/ \;
mkdir ${VER}/GvimExt32
cp src/GvimExt/gvimext.dll ${VER}/GvimExt32/
mkdir ${VER}/GvimExt64
cp src/GvimExt/gvimext.dll ${VER}/GvimExt64/

#C.  Copy gettext and iconv DLLs into the "vim82" directory
cp ../iconv/bin/libintl-8.dll ${VER}/
cp ../iconv/bin/libiconv-2.dll ${VER}/
cp ../iconv/bin/libintl-8.dll ${VER}/GvimExt32/
cp ../iconv/bin/libiconv-2.dll ${VER}/GvimExt32/
cp ../iconv/bin/libintl-8.dll ${VER}/GvimExt64/
cp ../iconv/bin/libiconv-2.dll ${VER}/GvimExt64/

#D.  Move the "vim82" directory into the Vim installation subdirectory
